# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.network "forwarded_port", guest: 8010, host: 8010
  # config.vm.synced_folder '.ssh', '/home/vagrant/.ssh'
  config.vm.provider 'virtualbox' do |vb|
    # We need to increase this to install lxml
    # vb.memory = 1024
  end
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../../../playbooks/vagrant-buildbot.yml"
    ansible.verbose = "vvvv"
  end
end
